/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = DotnetTraq.Client.FileParameter;
using OpenAPIDateConverter = DotnetTraq.Client.OpenAPIDateConverter;

namespace DotnetTraq.Model
{
    /// <summary>
    /// イベント配送結果
    /// </summary>
    /// <value>イベント配送結果</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum BotEventResult
    {
        /// <summary>
        /// Enum OK for value: ok
        /// </summary>
        [EnumMember(Value = "ok")]
        OK = 1,

        /// <summary>
        /// Enum NG for value: ng
        /// </summary>
        [EnumMember(Value = "ng")]
        NG = 2,

        /// <summary>
        /// Enum NetworkError for value: ne
        /// </summary>
        [EnumMember(Value = "ne")]
        NetworkError = 3,

        /// <summary>
        /// Enum Dropped for value: dp
        /// </summary>
        [EnumMember(Value = "dp")]
        Dropped = 4
    }

}
