// <auto-generated>
/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Traq.Client;

namespace Traq.Model
{
    /// <summary>
    /// traQ特有のユーザー詳細情報
    /// </summary>
    public partial class OIDCTraqUserInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OIDCTraqUserInfo" /> class.
        /// </summary>
        /// <param name="bio">自己紹介(biography)</param>
        /// <param name="groups">所属グループのUUIDの配列</param>
        /// <param name="tags">タグリスト</param>
        /// <param name="twitterId">Twitter ID</param>
        /// <param name="displayName">ユーザー表示名</param>
        /// <param name="iconFileId">アイコンファイルUUID</param>
        /// <param name="bot">BOTかどうか</param>
        /// <param name="state">state</param>
        /// <param name="permissions">所有している権限の配列</param>
        /// <param name="lastOnline">最終オンライン日時</param>
        /// <param name="homeChannel">ホームチャンネル</param>
        [JsonConstructor]
        public OIDCTraqUserInfo(string bio, List<Guid> groups, List<UserTag> tags, string twitterId, string displayName, Guid iconFileId, bool bot, UserAccountState state, List<UserPermission> permissions, DateTimeOffset? lastOnline = default, Guid? homeChannel = default)
        {
            Bio = bio;
            Groups = groups;
            Tags = tags;
            TwitterId = twitterId;
            DisplayName = displayName;
            IconFileId = iconFileId;
            Bot = bot;
            State = state;
            Permissions = permissions;
            LastOnline = lastOnline;
            HomeChannel = homeChannel;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [JsonPropertyName("state")]
        public UserAccountState State { get; set; }

        /// <summary>
        /// 自己紹介(biography)
        /// </summary>
        /// <value>自己紹介(biography)</value>
        [JsonPropertyName("bio")]
        public string Bio { get; set; }

        /// <summary>
        /// 所属グループのUUIDの配列
        /// </summary>
        /// <value>所属グループのUUIDの配列</value>
        [JsonPropertyName("groups")]
        public List<Guid> Groups { get; set; }

        /// <summary>
        /// タグリスト
        /// </summary>
        /// <value>タグリスト</value>
        [JsonPropertyName("tags")]
        public List<UserTag> Tags { get; set; }

        /// <summary>
        /// Twitter ID
        /// </summary>
        /// <value>Twitter ID</value>
        [JsonPropertyName("twitter_id")]
        public string TwitterId { get; set; }

        /// <summary>
        /// ユーザー表示名
        /// </summary>
        /// <value>ユーザー表示名</value>
        [JsonPropertyName("display_name")]
        public string DisplayName { get; set; }

        /// <summary>
        /// アイコンファイルUUID
        /// </summary>
        /// <value>アイコンファイルUUID</value>
        [JsonPropertyName("icon_file_id")]
        public Guid IconFileId { get; set; }

        /// <summary>
        /// BOTかどうか
        /// </summary>
        /// <value>BOTかどうか</value>
        [JsonPropertyName("bot")]
        public bool Bot { get; set; }

        /// <summary>
        /// 所有している権限の配列
        /// </summary>
        /// <value>所有している権限の配列</value>
        [JsonPropertyName("permissions")]
        public List<UserPermission> Permissions { get; set; }

        /// <summary>
        /// 最終オンライン日時
        /// </summary>
        /// <value>最終オンライン日時</value>
        [JsonPropertyName("last_online")]
        public DateTimeOffset? LastOnline { get; set; }

        /// <summary>
        /// ホームチャンネル
        /// </summary>
        /// <value>ホームチャンネル</value>
        [JsonPropertyName("home_channel")]
        public Guid? HomeChannel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OIDCTraqUserInfo {\n");
            sb.Append("  Bio: ").Append(Bio).Append("\n");
            sb.Append("  Groups: ").Append(Groups).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  TwitterId: ").Append(TwitterId).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  IconFileId: ").Append(IconFileId).Append("\n");
            sb.Append("  Bot: ").Append(Bot).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Permissions: ").Append(Permissions).Append("\n");
            sb.Append("  LastOnline: ").Append(LastOnline).Append("\n");
            sb.Append("  HomeChannel: ").Append(HomeChannel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Bio (string) maxLength
            if (this.Bio != null && this.Bio.Length > 1000)
            {
                yield return new ValidationResult("Invalid value for Bio, length must be less than 1000.", new [] { "Bio" });
            }

            if (this.TwitterId != null) {
                // TwitterId (string) pattern
                Regex regexTwitterId = new Regex(@"^[a-zA-Z0-9_]{1,15}$", RegexOptions.CultureInvariant);

                if (!regexTwitterId.Match(this.TwitterId).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TwitterId, must match a pattern of " + regexTwitterId, new [] { "TwitterId" });
                }
            }

            // DisplayName (string) maxLength
            if (this.DisplayName != null && this.DisplayName.Length > 32)
            {
                yield return new ValidationResult("Invalid value for DisplayName, length must be less than 32.", new [] { "DisplayName" });
            }

            // DisplayName (string) minLength
            if (this.DisplayName != null && this.DisplayName.Length < 0)
            {
                yield return new ValidationResult("Invalid value for DisplayName, length must be greater than 0.", new [] { "DisplayName" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OIDCTraqUserInfo" />
    /// </summary>
    public class OIDCTraqUserInfoJsonConverter : JsonConverter<OIDCTraqUserInfo>
    {
        /// <summary>
        /// The format to use to serialize LastOnline
        /// </summary>
        public static string LastOnlineFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="OIDCTraqUserInfo" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OIDCTraqUserInfo Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> bio = default;
            Option<List<Guid>?> groups = default;
            Option<List<UserTag>?> tags = default;
            Option<string?> twitterId = default;
            Option<string?> displayName = default;
            Option<Guid?> iconFileId = default;
            Option<bool?> bot = default;
            Option<UserAccountState?> state = default;
            Option<List<UserPermission>?> permissions = default;
            Option<DateTimeOffset?> lastOnline = default;
            Option<Guid?> homeChannel = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "bio":
                            bio = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "groups":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                groups = new Option<List<Guid>?>(JsonSerializer.Deserialize<List<Guid>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "tags":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                tags = new Option<List<UserTag>?>(JsonSerializer.Deserialize<List<UserTag>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "twitter_id":
                            twitterId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "display_name":
                            displayName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "icon_file_id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                iconFileId = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "bot":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                bot = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "state":
                            string? stateRawValue = utf8JsonReader.GetString();
                            if (stateRawValue != null)
                                state = new Option<UserAccountState?>(UserAccountStateValueConverter.FromStringOrDefault(stateRawValue));
                            break;
                        case "permissions":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                permissions = new Option<List<UserPermission>?>(JsonSerializer.Deserialize<List<UserPermission>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "last_online":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                lastOnline = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "home_channel":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                homeChannel = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!bio.IsSet)
                throw new ArgumentException("Property is required for class OIDCTraqUserInfo.", nameof(bio));

            if (!groups.IsSet)
                throw new ArgumentException("Property is required for class OIDCTraqUserInfo.", nameof(groups));

            if (!tags.IsSet)
                throw new ArgumentException("Property is required for class OIDCTraqUserInfo.", nameof(tags));

            if (!twitterId.IsSet)
                throw new ArgumentException("Property is required for class OIDCTraqUserInfo.", nameof(twitterId));

            if (!displayName.IsSet)
                throw new ArgumentException("Property is required for class OIDCTraqUserInfo.", nameof(displayName));

            if (!iconFileId.IsSet)
                throw new ArgumentException("Property is required for class OIDCTraqUserInfo.", nameof(iconFileId));

            if (!bot.IsSet)
                throw new ArgumentException("Property is required for class OIDCTraqUserInfo.", nameof(bot));

            if (!state.IsSet)
                throw new ArgumentException("Property is required for class OIDCTraqUserInfo.", nameof(state));

            if (!permissions.IsSet)
                throw new ArgumentException("Property is required for class OIDCTraqUserInfo.", nameof(permissions));

            if (!lastOnline.IsSet)
                throw new ArgumentException("Property is required for class OIDCTraqUserInfo.", nameof(lastOnline));

            if (!homeChannel.IsSet)
                throw new ArgumentException("Property is required for class OIDCTraqUserInfo.", nameof(homeChannel));

            if (bio.IsSet && bio.Value == null)
                throw new ArgumentNullException(nameof(bio), "Property is not nullable for class OIDCTraqUserInfo.");

            if (groups.IsSet && groups.Value == null)
                throw new ArgumentNullException(nameof(groups), "Property is not nullable for class OIDCTraqUserInfo.");

            if (tags.IsSet && tags.Value == null)
                throw new ArgumentNullException(nameof(tags), "Property is not nullable for class OIDCTraqUserInfo.");

            if (twitterId.IsSet && twitterId.Value == null)
                throw new ArgumentNullException(nameof(twitterId), "Property is not nullable for class OIDCTraqUserInfo.");

            if (displayName.IsSet && displayName.Value == null)
                throw new ArgumentNullException(nameof(displayName), "Property is not nullable for class OIDCTraqUserInfo.");

            if (iconFileId.IsSet && iconFileId.Value == null)
                throw new ArgumentNullException(nameof(iconFileId), "Property is not nullable for class OIDCTraqUserInfo.");

            if (bot.IsSet && bot.Value == null)
                throw new ArgumentNullException(nameof(bot), "Property is not nullable for class OIDCTraqUserInfo.");

            if (state.IsSet && state.Value == null)
                throw new ArgumentNullException(nameof(state), "Property is not nullable for class OIDCTraqUserInfo.");

            if (permissions.IsSet && permissions.Value == null)
                throw new ArgumentNullException(nameof(permissions), "Property is not nullable for class OIDCTraqUserInfo.");

            return new OIDCTraqUserInfo(bio.Value!, groups.Value!, tags.Value!, twitterId.Value!, displayName.Value!, iconFileId.Value!.Value!, bot.Value!.Value!, state.Value!.Value!, permissions.Value!, lastOnline.Value!, homeChannel.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="OIDCTraqUserInfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oIDCTraqUserInfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OIDCTraqUserInfo oIDCTraqUserInfo, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, oIDCTraqUserInfo, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OIDCTraqUserInfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oIDCTraqUserInfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OIDCTraqUserInfo oIDCTraqUserInfo, JsonSerializerOptions jsonSerializerOptions)
        {
            if (oIDCTraqUserInfo.Bio == null)
                throw new ArgumentNullException(nameof(oIDCTraqUserInfo.Bio), "Property is required for class OIDCTraqUserInfo.");

            if (oIDCTraqUserInfo.Groups == null)
                throw new ArgumentNullException(nameof(oIDCTraqUserInfo.Groups), "Property is required for class OIDCTraqUserInfo.");

            if (oIDCTraqUserInfo.Tags == null)
                throw new ArgumentNullException(nameof(oIDCTraqUserInfo.Tags), "Property is required for class OIDCTraqUserInfo.");

            if (oIDCTraqUserInfo.TwitterId == null)
                throw new ArgumentNullException(nameof(oIDCTraqUserInfo.TwitterId), "Property is required for class OIDCTraqUserInfo.");

            if (oIDCTraqUserInfo.DisplayName == null)
                throw new ArgumentNullException(nameof(oIDCTraqUserInfo.DisplayName), "Property is required for class OIDCTraqUserInfo.");

            if (oIDCTraqUserInfo.Permissions == null)
                throw new ArgumentNullException(nameof(oIDCTraqUserInfo.Permissions), "Property is required for class OIDCTraqUserInfo.");

            writer.WriteString("bio", oIDCTraqUserInfo.Bio);

            writer.WritePropertyName("groups");
            JsonSerializer.Serialize(writer, oIDCTraqUserInfo.Groups, jsonSerializerOptions);
            writer.WritePropertyName("tags");
            JsonSerializer.Serialize(writer, oIDCTraqUserInfo.Tags, jsonSerializerOptions);
            writer.WriteString("twitter_id", oIDCTraqUserInfo.TwitterId);

            writer.WriteString("display_name", oIDCTraqUserInfo.DisplayName);

            writer.WriteString("icon_file_id", oIDCTraqUserInfo.IconFileId);

            writer.WriteBoolean("bot", oIDCTraqUserInfo.Bot);

            var stateRawValue = UserAccountStateValueConverter.ToJsonValue(oIDCTraqUserInfo.State);
            writer.WriteNumber("state", stateRawValue);

            writer.WritePropertyName("permissions");
            JsonSerializer.Serialize(writer, oIDCTraqUserInfo.Permissions, jsonSerializerOptions);
            if (oIDCTraqUserInfo.LastOnline != null)
                writer.WriteString("last_online", oIDCTraqUserInfo.LastOnline.Value.ToString(LastOnlineFormat));
            else
                writer.WriteNull("last_online");

            if (oIDCTraqUserInfo.HomeChannel != null)
                writer.WriteString("home_channel", oIDCTraqUserInfo.HomeChannel.Value);
            else
                writer.WriteNull("home_channel");
        }
    }

    /// <summary>
    /// The OIDCTraqUserInfoSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(OIDCTraqUserInfo))]
    public partial class OIDCTraqUserInfoSerializationContext : JsonSerializerContext { }
}
