// <auto-generated>
/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Traq.Client;

namespace Traq.Model
{
    /// <summary>
    /// ユーザーのタグの編集リクエスト
    /// </summary>
    public partial class PatchUserTagRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PatchUserTagRequest" /> class.
        /// </summary>
        /// <param name="isLocked">タグのロック状態</param>
        [JsonConstructor]
        public PatchUserTagRequest(bool isLocked)
        {
            IsLocked = isLocked;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// タグのロック状態
        /// </summary>
        /// <value>タグのロック状態</value>
        [JsonPropertyName("isLocked")]
        public bool IsLocked { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PatchUserTagRequest {\n");
            sb.Append("  IsLocked: ").Append(IsLocked).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PatchUserTagRequest" />
    /// </summary>
    public class PatchUserTagRequestJsonConverter : JsonConverter<PatchUserTagRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="PatchUserTagRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PatchUserTagRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> isLocked = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "isLocked":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                isLocked = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!isLocked.IsSet)
                throw new ArgumentException("Property is required for class PatchUserTagRequest.", nameof(isLocked));

            if (isLocked.IsSet && isLocked.Value == null)
                throw new ArgumentNullException(nameof(isLocked), "Property is not nullable for class PatchUserTagRequest.");

            return new PatchUserTagRequest(isLocked.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="PatchUserTagRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="patchUserTagRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PatchUserTagRequest patchUserTagRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, patchUserTagRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PatchUserTagRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="patchUserTagRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PatchUserTagRequest patchUserTagRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteBoolean("isLocked", patchUserTagRequest.IsLocked);
        }
    }

    /// <summary>
    /// The PatchUserTagRequestSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(PatchUserTagRequest))]
    public partial class PatchUserTagRequestSerializationContext : JsonSerializerContext { }
}
