/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = DotnetTraq.Client.FileParameter;
using OpenAPIDateConverter = DotnetTraq.Client.OpenAPIDateConverter;

namespace DotnetTraq.Model
{
    /// <summary>
    /// ユーザータグ追加リクエスト
    /// </summary>
    [DataContract(Name = "PostUserTagRequest")]
    public partial class PostUserTagRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostUserTagRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PostUserTagRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PostUserTagRequest" /> class.
        /// </summary>
        /// <param name="tag">タグ文字列 (required).</param>
        public PostUserTagRequest(string tag = default(string))
        {
            // to ensure "tag" is required (not null)
            if (tag == null)
            {
                throw new ArgumentNullException("tag is a required property for PostUserTagRequest and cannot be null");
            }
            this.Tag = tag;
        }

        /// <summary>
        /// タグ文字列
        /// </summary>
        /// <value>タグ文字列</value>
        [DataMember(Name = "tag", IsRequired = true, EmitDefaultValue = true)]
        public string Tag { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostUserTagRequest {\n");
            sb.Append("  Tag: ").Append(Tag).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Tag (string) maxLength
            if (this.Tag != null && this.Tag.Length > 30)
            {
                yield return new ValidationResult("Invalid value for Tag, length must be less than 30.", new [] { "Tag" });
            }

            // Tag (string) minLength
            if (this.Tag != null && this.Tag.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Tag, length must be greater than 1.", new [] { "Tag" });
            }

            yield break;
        }
    }

}
