/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Traq.Client.FileParameter;
using OpenAPIDateConverter = Traq.Client.OpenAPIDateConverter;

namespace Traq.Model
{
    /// <summary>
    /// スタンプを押すリクエスト
    /// </summary>
    [DataContract(Name = "PostMessageStampRequest")]
    public partial class PostMessageStampRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostMessageStampRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PostMessageStampRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PostMessageStampRequest" /> class.
        /// </summary>
        /// <param name="count">押す数 (required).</param>
        public PostMessageStampRequest(int count = default(int))
        {
            this.Count = count;
        }

        /// <summary>
        /// 押す数
        /// </summary>
        /// <value>押す数</value>
        [DataMember(Name = "count", IsRequired = true, EmitDefaultValue = true)]
        public int Count { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostMessageStampRequest {\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Count (int) maximum
            if (this.Count > (int)100)
            {
                yield return new ValidationResult("Invalid value for Count, must be a value less than or equal to 100.", new[] { "Count" });
            }

            // Count (int) minimum
            if (this.Count < (int)1)
            {
                yield return new ValidationResult("Invalid value for Count, must be a value greater than or equal to 1.", new[] { "Count" });
            }

            yield break;
        }
    }

}
