// <auto-generated>
/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Traq.Client;

namespace Traq.Model
{
    /// <summary>
    /// Qallのサウンドボードアイテムが削除された
    /// </summary>
    public partial class QallSoundboardItemDeletedEvent : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QallSoundboardItemDeletedEvent" /> class.
        /// </summary>
        /// <param name="soundId">削除されたサウンドボードアイテムのId</param>
        [JsonConstructor]
        public QallSoundboardItemDeletedEvent(Guid soundId)
        {
            SoundId = soundId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// 削除されたサウンドボードアイテムのId
        /// </summary>
        /// <value>削除されたサウンドボードアイテムのId</value>
        [JsonPropertyName("soundId")]
        public Guid SoundId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QallSoundboardItemDeletedEvent {\n");
            sb.Append("  SoundId: ").Append(SoundId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="QallSoundboardItemDeletedEvent" />
    /// </summary>
    public class QallSoundboardItemDeletedEventJsonConverter : JsonConverter<QallSoundboardItemDeletedEvent>
    {
        /// <summary>
        /// Deserializes json to <see cref="QallSoundboardItemDeletedEvent" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override QallSoundboardItemDeletedEvent Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> soundId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "soundId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                soundId = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!soundId.IsSet)
                throw new ArgumentException("Property is required for class QallSoundboardItemDeletedEvent.", nameof(soundId));

            if (soundId.IsSet && soundId.Value == null)
                throw new ArgumentNullException(nameof(soundId), "Property is not nullable for class QallSoundboardItemDeletedEvent.");

            return new QallSoundboardItemDeletedEvent(soundId.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="QallSoundboardItemDeletedEvent" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="qallSoundboardItemDeletedEvent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, QallSoundboardItemDeletedEvent qallSoundboardItemDeletedEvent, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, qallSoundboardItemDeletedEvent, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="QallSoundboardItemDeletedEvent" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="qallSoundboardItemDeletedEvent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, QallSoundboardItemDeletedEvent qallSoundboardItemDeletedEvent, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteString("soundId", qallSoundboardItemDeletedEvent.SoundId);
        }
    }

    /// <summary>
    /// The QallSoundboardItemDeletedEventSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(QallSoundboardItemDeletedEvent))]
    public partial class QallSoundboardItemDeletedEventSerializationContext : JsonSerializerContext { }
}
