/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Traq.Client.FileParameter;
using OpenAPIDateConverter = Traq.Client.OpenAPIDateConverter;

namespace Traq.Model
{
    /// <summary>
    /// QallParticipantRequestUsersInner
    /// </summary>
    [DataContract(Name = "qallParticipantRequest_users_inner")]
    public partial class QallParticipantRequestUsersInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QallParticipantRequestUsersInner" /> class.
        /// </summary>
        /// <param name="userId">ユーザーID.</param>
        /// <param name="canPublish">発言権限.</param>
        public QallParticipantRequestUsersInner(string userId = default(string), bool canPublish = default(bool))
        {
            this.UserId = userId;
            this.CanPublish = canPublish;
        }

        /// <summary>
        /// ユーザーID
        /// </summary>
        /// <value>ユーザーID</value>
        [DataMember(Name = "userId", EmitDefaultValue = false)]
        public string UserId { get; set; }

        /// <summary>
        /// 発言権限
        /// </summary>
        /// <value>発言権限</value>
        [DataMember(Name = "canPublish", EmitDefaultValue = true)]
        public bool CanPublish { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QallParticipantRequestUsersInner {\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  CanPublish: ").Append(CanPublish).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
