// <auto-generated>
/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Traq.Client;

namespace Traq.Model
{
    /// <summary>
    /// SoundboardUploadResponse
    /// </summary>
    public partial class SoundboardUploadResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SoundboardUploadResponse" /> class.
        /// </summary>
        /// <param name="soundId">登録されたサウンドID (ファイル名)</param>
        [JsonConstructor]
        public SoundboardUploadResponse(string soundId)
        {
            SoundId = soundId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// 登録されたサウンドID (ファイル名)
        /// </summary>
        /// <value>登録されたサウンドID (ファイル名)</value>
        [JsonPropertyName("soundId")]
        public string SoundId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SoundboardUploadResponse {\n");
            sb.Append("  SoundId: ").Append(SoundId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SoundboardUploadResponse" />
    /// </summary>
    public class SoundboardUploadResponseJsonConverter : JsonConverter<SoundboardUploadResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="SoundboardUploadResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SoundboardUploadResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> soundId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "soundId":
                            soundId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!soundId.IsSet)
                throw new ArgumentException("Property is required for class SoundboardUploadResponse.", nameof(soundId));

            if (soundId.IsSet && soundId.Value == null)
                throw new ArgumentNullException(nameof(soundId), "Property is not nullable for class SoundboardUploadResponse.");

            return new SoundboardUploadResponse(soundId.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SoundboardUploadResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="soundboardUploadResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SoundboardUploadResponse soundboardUploadResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, soundboardUploadResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SoundboardUploadResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="soundboardUploadResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SoundboardUploadResponse soundboardUploadResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (soundboardUploadResponse.SoundId == null)
                throw new ArgumentNullException(nameof(soundboardUploadResponse.SoundId), "Property is required for class SoundboardUploadResponse.");

            writer.WriteString("soundId", soundboardUploadResponse.SoundId);
        }
    }

    /// <summary>
    /// The SoundboardUploadResponseSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(SoundboardUploadResponse))]
    public partial class SoundboardUploadResponseSerializationContext : JsonSerializerContext { }
}
