/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Traq.Client.FileParameter;
using OpenAPIDateConverter = Traq.Client.OpenAPIDateConverter;

namespace Traq.Model
{
    /// <summary>
    /// ThumbnailInfo
    /// </summary>
    [DataContract(Name = "ThumbnailInfo")]
    public partial class ThumbnailInfo : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public ThumbnailType Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ThumbnailInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ThumbnailInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ThumbnailInfo" /> class.
        /// </summary>
        /// <param name="type">type (required).</param>
        /// <param name="mime">MIMEタイプ (required).</param>
        /// <param name="width">サムネイル幅.</param>
        /// <param name="height">サムネイル高さ.</param>
        public ThumbnailInfo(ThumbnailType type = default(ThumbnailType), string mime = default(string), int width = default(int), int height = default(int))
        {
            this.Type = type;
            // to ensure "mime" is required (not null)
            if (mime == null)
            {
                throw new ArgumentNullException("mime is a required property for ThumbnailInfo and cannot be null");
            }
            this.Mime = mime;
            this.Width = width;
            this.Height = height;
        }

        /// <summary>
        /// MIMEタイプ
        /// </summary>
        /// <value>MIMEタイプ</value>
        [DataMember(Name = "mime", IsRequired = true, EmitDefaultValue = true)]
        public string Mime { get; set; }

        /// <summary>
        /// サムネイル幅
        /// </summary>
        /// <value>サムネイル幅</value>
        [DataMember(Name = "width", EmitDefaultValue = false)]
        public int Width { get; set; }

        /// <summary>
        /// サムネイル高さ
        /// </summary>
        /// <value>サムネイル高さ</value>
        [DataMember(Name = "height", EmitDefaultValue = false)]
        public int Height { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ThumbnailInfo {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Mime: ").Append(Mime).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
