/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Traq.Client.FileParameter;
using OpenAPIDateConverter = Traq.Client.OpenAPIDateConverter;

namespace Traq.Model
{
    /// <summary>
    /// ユーザー権限
    /// </summary>
    /// <value>ユーザー権限</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum UserPermission
    {
        /// <summary>
        /// Enum GetWebhook for value: get_webhook
        /// </summary>
        [EnumMember(Value = "get_webhook")]
        GetWebhook = 1,

        /// <summary>
        /// Enum CreateWebhook for value: create_webhook
        /// </summary>
        [EnumMember(Value = "create_webhook")]
        CreateWebhook = 2,

        /// <summary>
        /// Enum EditWebhook for value: edit_webhook
        /// </summary>
        [EnumMember(Value = "edit_webhook")]
        EditWebhook = 3,

        /// <summary>
        /// Enum DeleteWebhook for value: delete_webhook
        /// </summary>
        [EnumMember(Value = "delete_webhook")]
        DeleteWebhook = 4,

        /// <summary>
        /// Enum AccessOthersWebhook for value: access_others_webhook
        /// </summary>
        [EnumMember(Value = "access_others_webhook")]
        AccessOthersWebhook = 5,

        /// <summary>
        /// Enum GetBot for value: get_bot
        /// </summary>
        [EnumMember(Value = "get_bot")]
        GetBot = 6,

        /// <summary>
        /// Enum CreateBot for value: create_bot
        /// </summary>
        [EnumMember(Value = "create_bot")]
        CreateBot = 7,

        /// <summary>
        /// Enum EditBot for value: edit_bot
        /// </summary>
        [EnumMember(Value = "edit_bot")]
        EditBot = 8,

        /// <summary>
        /// Enum DeleteBot for value: delete_bot
        /// </summary>
        [EnumMember(Value = "delete_bot")]
        DeleteBot = 9,

        /// <summary>
        /// Enum AccessOthersBot for value: access_others_bot
        /// </summary>
        [EnumMember(Value = "access_others_bot")]
        AccessOthersBot = 10,

        /// <summary>
        /// Enum BotActionJoinChannel for value: bot_action_join_channel
        /// </summary>
        [EnumMember(Value = "bot_action_join_channel")]
        BotActionJoinChannel = 11,

        /// <summary>
        /// Enum BotActionLeaveChannel for value: bot_action_leave_channel
        /// </summary>
        [EnumMember(Value = "bot_action_leave_channel")]
        BotActionLeaveChannel = 12,

        /// <summary>
        /// Enum CreateChannel for value: create_channel
        /// </summary>
        [EnumMember(Value = "create_channel")]
        CreateChannel = 13,

        /// <summary>
        /// Enum GetChannel for value: get_channel
        /// </summary>
        [EnumMember(Value = "get_channel")]
        GetChannel = 14,

        /// <summary>
        /// Enum EditChannel for value: edit_channel
        /// </summary>
        [EnumMember(Value = "edit_channel")]
        EditChannel = 15,

        /// <summary>
        /// Enum DeleteChannel for value: delete_channel
        /// </summary>
        [EnumMember(Value = "delete_channel")]
        DeleteChannel = 16,

        /// <summary>
        /// Enum ChangeParentChannel for value: change_parent_channel
        /// </summary>
        [EnumMember(Value = "change_parent_channel")]
        ChangeParentChannel = 17,

        /// <summary>
        /// Enum EditChannelTopic for value: edit_channel_topic
        /// </summary>
        [EnumMember(Value = "edit_channel_topic")]
        EditChannelTopic = 18,

        /// <summary>
        /// Enum GetChannelStar for value: get_channel_star
        /// </summary>
        [EnumMember(Value = "get_channel_star")]
        GetChannelStar = 19,

        /// <summary>
        /// Enum EditChannelStar for value: edit_channel_star
        /// </summary>
        [EnumMember(Value = "edit_channel_star")]
        EditChannelStar = 20,

        /// <summary>
        /// Enum GetMyTokens for value: get_my_tokens
        /// </summary>
        [EnumMember(Value = "get_my_tokens")]
        GetMyTokens = 21,

        /// <summary>
        /// Enum RevokeMyToken for value: revoke_my_token
        /// </summary>
        [EnumMember(Value = "revoke_my_token")]
        RevokeMyToken = 22,

        /// <summary>
        /// Enum GetClients for value: get_clients
        /// </summary>
        [EnumMember(Value = "get_clients")]
        GetClients = 23,

        /// <summary>
        /// Enum CreateClient for value: create_client
        /// </summary>
        [EnumMember(Value = "create_client")]
        CreateClient = 24,

        /// <summary>
        /// Enum EditMyClient for value: edit_my_client
        /// </summary>
        [EnumMember(Value = "edit_my_client")]
        EditMyClient = 25,

        /// <summary>
        /// Enum DeleteMyClient for value: delete_my_client
        /// </summary>
        [EnumMember(Value = "delete_my_client")]
        DeleteMyClient = 26,

        /// <summary>
        /// Enum ManageOthersClient for value: manage_others_client
        /// </summary>
        [EnumMember(Value = "manage_others_client")]
        ManageOthersClient = 27,

        /// <summary>
        /// Enum UploadFile for value: upload_file
        /// </summary>
        [EnumMember(Value = "upload_file")]
        UploadFile = 28,

        /// <summary>
        /// Enum DownloadFile for value: download_file
        /// </summary>
        [EnumMember(Value = "download_file")]
        DownloadFile = 29,

        /// <summary>
        /// Enum DeleteFile for value: delete_file
        /// </summary>
        [EnumMember(Value = "delete_file")]
        DeleteFile = 30,

        /// <summary>
        /// Enum GetMessage for value: get_message
        /// </summary>
        [EnumMember(Value = "get_message")]
        GetMessage = 31,

        /// <summary>
        /// Enum PostMessage for value: post_message
        /// </summary>
        [EnumMember(Value = "post_message")]
        PostMessage = 32,

        /// <summary>
        /// Enum EditMessage for value: edit_message
        /// </summary>
        [EnumMember(Value = "edit_message")]
        EditMessage = 33,

        /// <summary>
        /// Enum DeleteMessage for value: delete_message
        /// </summary>
        [EnumMember(Value = "delete_message")]
        DeleteMessage = 34,

        /// <summary>
        /// Enum ReportMessage for value: report_message
        /// </summary>
        [EnumMember(Value = "report_message")]
        ReportMessage = 35,

        /// <summary>
        /// Enum GetMessageReports for value: get_message_reports
        /// </summary>
        [EnumMember(Value = "get_message_reports")]
        GetMessageReports = 36,

        /// <summary>
        /// Enum CreateMessagePin for value: create_message_pin
        /// </summary>
        [EnumMember(Value = "create_message_pin")]
        CreateMessagePin = 37,

        /// <summary>
        /// Enum DeleteMessagePin for value: delete_message_pin
        /// </summary>
        [EnumMember(Value = "delete_message_pin")]
        DeleteMessagePin = 38,

        /// <summary>
        /// Enum GetChannelSubscription for value: get_channel_subscription
        /// </summary>
        [EnumMember(Value = "get_channel_subscription")]
        GetChannelSubscription = 39,

        /// <summary>
        /// Enum EditChannelSubscription for value: edit_channel_subscription
        /// </summary>
        [EnumMember(Value = "edit_channel_subscription")]
        EditChannelSubscription = 40,

        /// <summary>
        /// Enum ConnectNotificationStream for value: connect_notification_stream
        /// </summary>
        [EnumMember(Value = "connect_notification_stream")]
        ConnectNotificationStream = 41,

        /// <summary>
        /// Enum RegisterFCMDevice for value: register_fcm_device
        /// </summary>
        [EnumMember(Value = "register_fcm_device")]
        RegisterFCMDevice = 42,

        /// <summary>
        /// Enum GetStamp for value: get_stamp
        /// </summary>
        [EnumMember(Value = "get_stamp")]
        GetStamp = 43,

        /// <summary>
        /// Enum CreateStamp for value: create_stamp
        /// </summary>
        [EnumMember(Value = "create_stamp")]
        CreateStamp = 44,

        /// <summary>
        /// Enum EditStamp for value: edit_stamp
        /// </summary>
        [EnumMember(Value = "edit_stamp")]
        EditStamp = 45,

        /// <summary>
        /// Enum EditStampCreatedByOthers for value: edit_stamp_created_by_others
        /// </summary>
        [EnumMember(Value = "edit_stamp_created_by_others")]
        EditStampCreatedByOthers = 46,

        /// <summary>
        /// Enum DeleteStamp for value: delete_stamp
        /// </summary>
        [EnumMember(Value = "delete_stamp")]
        DeleteStamp = 47,

        /// <summary>
        /// Enum DeleteMyStamp for value: delete_my_stamp
        /// </summary>
        [EnumMember(Value = "delete_my_stamp")]
        DeleteMyStamp = 48,

        /// <summary>
        /// Enum AddMessageStamp for value: add_message_stamp
        /// </summary>
        [EnumMember(Value = "add_message_stamp")]
        AddMessageStamp = 49,

        /// <summary>
        /// Enum RemoveMessageStamp for value: remove_message_stamp
        /// </summary>
        [EnumMember(Value = "remove_message_stamp")]
        RemoveMessageStamp = 50,

        /// <summary>
        /// Enum GetMyStampHistory for value: get_my_stamp_history
        /// </summary>
        [EnumMember(Value = "get_my_stamp_history")]
        GetMyStampHistory = 51,

        /// <summary>
        /// Enum GetStampPalette for value: get_stamp_palette
        /// </summary>
        [EnumMember(Value = "get_stamp_palette")]
        GetStampPalette = 52,

        /// <summary>
        /// Enum CreateStampPalette for value: create_stamp_palette
        /// </summary>
        [EnumMember(Value = "create_stamp_palette")]
        CreateStampPalette = 53,

        /// <summary>
        /// Enum EditStampPalette for value: edit_stamp_palette
        /// </summary>
        [EnumMember(Value = "edit_stamp_palette")]
        EditStampPalette = 54,

        /// <summary>
        /// Enum DeleteStampPalette for value: delete_stamp_palette
        /// </summary>
        [EnumMember(Value = "delete_stamp_palette")]
        DeleteStampPalette = 55,

        /// <summary>
        /// Enum GetUser for value: get_user
        /// </summary>
        [EnumMember(Value = "get_user")]
        GetUser = 56,

        /// <summary>
        /// Enum RegisterUser for value: register_user
        /// </summary>
        [EnumMember(Value = "register_user")]
        RegisterUser = 57,

        /// <summary>
        /// Enum GetMe for value: get_me
        /// </summary>
        [EnumMember(Value = "get_me")]
        GetMe = 58,

        /// <summary>
        /// Enum GetOIDCUserInfo for value: get_oidc_userinfo
        /// </summary>
        [EnumMember(Value = "get_oidc_userinfo")]
        GetOIDCUserInfo = 59,

        /// <summary>
        /// Enum EditMe for value: edit_me
        /// </summary>
        [EnumMember(Value = "edit_me")]
        EditMe = 60,

        /// <summary>
        /// Enum ChangeMyIcon for value: change_my_icon
        /// </summary>
        [EnumMember(Value = "change_my_icon")]
        ChangeMyIcon = 61,

        /// <summary>
        /// Enum ChangeMyPassword for value: change_my_password
        /// </summary>
        [EnumMember(Value = "change_my_password")]
        ChangeMyPassword = 62,

        /// <summary>
        /// Enum EditOtherUsers for value: edit_other_users
        /// </summary>
        [EnumMember(Value = "edit_other_users")]
        EditOtherUsers = 63,

        /// <summary>
        /// Enum GetUserQRCode for value: get_user_qr_code
        /// </summary>
        [EnumMember(Value = "get_user_qr_code")]
        GetUserQRCode = 64,

        /// <summary>
        /// Enum GetUserTag for value: get_user_tag
        /// </summary>
        [EnumMember(Value = "get_user_tag")]
        GetUserTag = 65,

        /// <summary>
        /// Enum EditUserTag for value: edit_user_tag
        /// </summary>
        [EnumMember(Value = "edit_user_tag")]
        EditUserTag = 66,

        /// <summary>
        /// Enum GetUserGroup for value: get_user_group
        /// </summary>
        [EnumMember(Value = "get_user_group")]
        GetUserGroup = 67,

        /// <summary>
        /// Enum CreateUserGroup for value: create_user_group
        /// </summary>
        [EnumMember(Value = "create_user_group")]
        CreateUserGroup = 68,

        /// <summary>
        /// Enum CreateSpecialUserGroup for value: create_special_user_group
        /// </summary>
        [EnumMember(Value = "create_special_user_group")]
        CreateSpecialUserGroup = 69,

        /// <summary>
        /// Enum EditUserGroup for value: edit_user_group
        /// </summary>
        [EnumMember(Value = "edit_user_group")]
        EditUserGroup = 70,

        /// <summary>
        /// Enum DeleteUserGroup for value: delete_user_group
        /// </summary>
        [EnumMember(Value = "delete_user_group")]
        DeleteUserGroup = 71,

        /// <summary>
        /// Enum AllUserGroupsAdmin for value: edit_others_user_group
        /// </summary>
        [EnumMember(Value = "edit_others_user_group")]
        AllUserGroupsAdmin = 72,

        /// <summary>
        /// Enum WebRTC for value: web_rtc
        /// </summary>
        [EnumMember(Value = "web_rtc")]
        WebRTC = 73,

        /// <summary>
        /// Enum GetMySessions for value: get_my_sessions
        /// </summary>
        [EnumMember(Value = "get_my_sessions")]
        GetMySessions = 74,

        /// <summary>
        /// Enum DeleteMySessions for value: delete_my_sessions
        /// </summary>
        [EnumMember(Value = "delete_my_sessions")]
        DeleteMySessions = 75,

        /// <summary>
        /// Enum GetMyExternalAccount for value: get_my_external_account
        /// </summary>
        [EnumMember(Value = "get_my_external_account")]
        GetMyExternalAccount = 76,

        /// <summary>
        /// Enum EditMyExternalAccount for value: edit_my_external_account
        /// </summary>
        [EnumMember(Value = "edit_my_external_account")]
        EditMyExternalAccount = 77,

        /// <summary>
        /// Enum GetUnread for value: get_unread
        /// </summary>
        [EnumMember(Value = "get_unread")]
        GetUnread = 78,

        /// <summary>
        /// Enum DeleteUnread for value: delete_unread
        /// </summary>
        [EnumMember(Value = "delete_unread")]
        DeleteUnread = 79,

        /// <summary>
        /// Enum GetClipFolder for value: get_clip_folder
        /// </summary>
        [EnumMember(Value = "get_clip_folder")]
        GetClipFolder = 80,

        /// <summary>
        /// Enum CreateClipFolder for value: create_clip_folder
        /// </summary>
        [EnumMember(Value = "create_clip_folder")]
        CreateClipFolder = 81,

        /// <summary>
        /// Enum EditClipFolder for value: edit_clip_folder
        /// </summary>
        [EnumMember(Value = "edit_clip_folder")]
        EditClipFolder = 82,

        /// <summary>
        /// Enum DeleteClipFolder for value: delete_clip_folder
        /// </summary>
        [EnumMember(Value = "delete_clip_folder")]
        DeleteClipFolder = 83
    }

}
