// <auto-generated>
/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Traq.Client;

namespace Traq.Model
{
    /// <summary>
    /// ユーザー情報
    /// </summary>
    public partial class User : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="User" /> class.
        /// </summary>
        /// <param name="id">ユーザーUUID</param>
        /// <param name="name">ユーザー名</param>
        /// <param name="displayName">ユーザー表示名</param>
        /// <param name="iconFileId">アイコンファイルUUID</param>
        /// <param name="bot">BOTかどうか</param>
        /// <param name="state">state</param>
        /// <param name="updatedAt">更新日時</param>
        [JsonConstructor]
        public User(Guid id, string name, string displayName, Guid iconFileId, bool bot, UserAccountState state, DateTimeOffset updatedAt)
        {
            Id = id;
            Name = name;
            DisplayName = displayName;
            IconFileId = iconFileId;
            Bot = bot;
            State = state;
            UpdatedAt = updatedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [JsonPropertyName("state")]
        public UserAccountState State { get; set; }

        /// <summary>
        /// ユーザーUUID
        /// </summary>
        /// <value>ユーザーUUID</value>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// ユーザー名
        /// </summary>
        /// <value>ユーザー名</value>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// ユーザー表示名
        /// </summary>
        /// <value>ユーザー表示名</value>
        [JsonPropertyName("displayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// アイコンファイルUUID
        /// </summary>
        /// <value>アイコンファイルUUID</value>
        [JsonPropertyName("iconFileId")]
        public Guid IconFileId { get; set; }

        /// <summary>
        /// BOTかどうか
        /// </summary>
        /// <value>BOTかどうか</value>
        [JsonPropertyName("bot")]
        public bool Bot { get; set; }

        /// <summary>
        /// 更新日時
        /// </summary>
        /// <value>更新日時</value>
        [JsonPropertyName("updatedAt")]
        public DateTimeOffset UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class User {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  IconFileId: ").Append(IconFileId).Append("\n");
            sb.Append("  Bot: ").Append(Bot).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.Name != null) {
                // Name (string) pattern
                Regex regexName = new Regex(@"^[a-zA-Z0-9_-]{1,32}$", RegexOptions.CultureInvariant);

                if (!regexName.Match(this.Name).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, must match a pattern of " + regexName, new [] { "Name" });
                }
            }

            // DisplayName (string) maxLength
            if (this.DisplayName != null && this.DisplayName.Length > 32)
            {
                yield return new ValidationResult("Invalid value for DisplayName, length must be less than 32.", new [] { "DisplayName" });
            }

            // DisplayName (string) minLength
            if (this.DisplayName != null && this.DisplayName.Length < 0)
            {
                yield return new ValidationResult("Invalid value for DisplayName, length must be greater than 0.", new [] { "DisplayName" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="User" />
    /// </summary>
    public class UserJsonConverter : JsonConverter<User>
    {
        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public static string UpdatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="User" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override User Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<string?> name = default;
            Option<string?> displayName = default;
            Option<Guid?> iconFileId = default;
            Option<bool?> bot = default;
            Option<UserAccountState?> state = default;
            Option<DateTimeOffset?> updatedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                id = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "displayName":
                            displayName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "iconFileId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                iconFileId = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "bot":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                bot = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "state":
                            string? stateRawValue = utf8JsonReader.GetString();
                            if (stateRawValue != null)
                                state = new Option<UserAccountState?>(UserAccountStateValueConverter.FromStringOrDefault(stateRawValue));
                            break;
                        case "updatedAt":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                updatedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class User.", nameof(id));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class User.", nameof(name));

            if (!displayName.IsSet)
                throw new ArgumentException("Property is required for class User.", nameof(displayName));

            if (!iconFileId.IsSet)
                throw new ArgumentException("Property is required for class User.", nameof(iconFileId));

            if (!bot.IsSet)
                throw new ArgumentException("Property is required for class User.", nameof(bot));

            if (!state.IsSet)
                throw new ArgumentException("Property is required for class User.", nameof(state));

            if (!updatedAt.IsSet)
                throw new ArgumentException("Property is required for class User.", nameof(updatedAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class User.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class User.");

            if (displayName.IsSet && displayName.Value == null)
                throw new ArgumentNullException(nameof(displayName), "Property is not nullable for class User.");

            if (iconFileId.IsSet && iconFileId.Value == null)
                throw new ArgumentNullException(nameof(iconFileId), "Property is not nullable for class User.");

            if (bot.IsSet && bot.Value == null)
                throw new ArgumentNullException(nameof(bot), "Property is not nullable for class User.");

            if (state.IsSet && state.Value == null)
                throw new ArgumentNullException(nameof(state), "Property is not nullable for class User.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class User.");

            return new User(id.Value!.Value!, name.Value!, displayName.Value!, iconFileId.Value!.Value!, bot.Value!.Value!, state.Value!.Value!, updatedAt.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="User" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="user"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, User user, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, user, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="User" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="user"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, User user, JsonSerializerOptions jsonSerializerOptions)
        {
            if (user.Name == null)
                throw new ArgumentNullException(nameof(user.Name), "Property is required for class User.");

            if (user.DisplayName == null)
                throw new ArgumentNullException(nameof(user.DisplayName), "Property is required for class User.");

            writer.WriteString("id", user.Id);

            writer.WriteString("name", user.Name);

            writer.WriteString("displayName", user.DisplayName);

            writer.WriteString("iconFileId", user.IconFileId);

            writer.WriteBoolean("bot", user.Bot);

            var stateRawValue = UserAccountStateValueConverter.ToJsonValue(user.State);
            writer.WriteNumber("state", stateRawValue);

            writer.WriteString("updatedAt", user.UpdatedAt.ToString(UpdatedAtFormat));
        }
    }

    /// <summary>
    /// The UserSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(User))]
    public partial class UserSerializationContext : JsonSerializerContext { }
}
