// <auto-generated/>
using System;
using System.Runtime.Serialization;
namespace Traq.Stamps
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
    public enum GetTypeQueryParameterType
#pragma warning restore CS1591
    {
        [EnumMember(Value = "unicode")]
#pragma warning disable CS1591
        Unicode,
#pragma warning restore CS1591
        [EnumMember(Value = "original")]
#pragma warning disable CS1591
        Original,
#pragma warning restore CS1591
    }
}
