// <auto-generated/>
using System;
using System.Runtime.Serialization;
namespace Traq.Models
{
    /// <summary>閲覧状態</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChannelViewState
    {
        [EnumMember(Value = "none")]
#pragma warning disable CS1591
        None,
#pragma warning restore CS1591
        [EnumMember(Value = "stale_viewing")]
#pragma warning disable CS1591
        Stale_viewing,
#pragma warning restore CS1591
        [EnumMember(Value = "monitoring")]
#pragma warning disable CS1591
        Monitoring,
#pragma warning restore CS1591
        [EnumMember(Value = "editing")]
#pragma warning disable CS1591
        Editing,
#pragma warning restore CS1591
    }
}
