// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Traq.Models
{
    /// <summary>OAuth2スコープ</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OAuth2Scope
    {
        [EnumMember(Value = "openid")]
        #pragma warning disable CS1591
        Openid,
        #pragma warning restore CS1591
        [EnumMember(Value = "profile")]
        #pragma warning disable CS1591
        Profile,
        #pragma warning restore CS1591
        [EnumMember(Value = "read")]
        #pragma warning disable CS1591
        Read,
        #pragma warning restore CS1591
        [EnumMember(Value = "write")]
        #pragma warning disable CS1591
        Write,
        #pragma warning restore CS1591
        [EnumMember(Value = "manage_bot")]
        #pragma warning disable CS1591
        Manage_bot,
        #pragma warning restore CS1591
    }
}
