// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System;
using System.Collections.Generic;
using System.IO;
namespace Traq.Models
{
    /// <summary>
    /// ユーザー統計情報
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserStats : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>統計情報日時</summary>
        public DateTimeOffset? Datetime { get; set; }
        /// <summary>ユーザーのスタンプ統計情報</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Traq.Models.UserStatsStamp>? Stamps { get; set; }
#nullable restore
#else
        public List<global::Traq.Models.UserStatsStamp> Stamps { get; set; }
#endif
        /// <summary>ユーザーの総投稿メッセージ数(削除されたものも含む)</summary>
        public long? TotalMessageCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Traq.Models.UserStats"/> and sets the default values.
        /// </summary>
        public UserStats()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Traq.Models.UserStats"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Traq.Models.UserStats CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Traq.Models.UserStats();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "datetime", n => { Datetime = n.GetDateTimeOffsetValue(); } },
                { "stamps", n => { Stamps = n.GetCollectionOfObjectValues<global::Traq.Models.UserStatsStamp>(global::Traq.Models.UserStatsStamp.CreateFromDiscriminatorValue)?.AsList(); } },
                { "totalMessageCount", n => { TotalMessageCount = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("datetime", Datetime);
            writer.WriteCollectionOfObjectValues<global::Traq.Models.UserStatsStamp>("stamps", Stamps);
            writer.WriteLongValue("totalMessageCount", TotalMessageCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
