// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System;
using System.Collections.Generic;
using System.IO;
namespace Traq.Models
{
    /// <summary>
    /// skyway用認証リクエストリザルト
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebRTCAuthenticateResult : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>認証トークン</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthToken { get; set; }
#nullable restore
#else
        public string AuthToken { get; set; }
#endif
        /// <summary>ピアID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PeerId { get; set; }
#nullable restore
#else
        public string PeerId { get; set; }
#endif
        /// <summary>タイムスタンプ</summary>
        public long? Timestamp { get; set; }
        /// <summary>TTL</summary>
        public int? Ttl { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Traq.Models.WebRTCAuthenticateResult"/> and sets the default values.
        /// </summary>
        public WebRTCAuthenticateResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Traq.Models.WebRTCAuthenticateResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Traq.Models.WebRTCAuthenticateResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Traq.Models.WebRTCAuthenticateResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authToken", n => { AuthToken = n.GetStringValue(); } },
                { "peerId", n => { PeerId = n.GetStringValue(); } },
                { "timestamp", n => { Timestamp = n.GetLongValue(); } },
                { "ttl", n => { Ttl = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("authToken", AuthToken);
            writer.WriteStringValue("peerId", PeerId);
            writer.WriteLongValue("timestamp", Timestamp);
            writer.WriteIntValue("ttl", Ttl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
