// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Extensions;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Traq.Qall.Endpoints;
using Traq.Qall.Rooms;
using Traq.Qall.Soundboard;
using Traq.Qall.Token;
using Traq.Qall.Webhook;
namespace Traq.Qall
{
    /// <summary>
    /// Builds and executes requests for operations under \qall
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QallRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The endpoints property</summary>
        public global::Traq.Qall.Endpoints.EndpointsRequestBuilder Endpoints
        {
            get => new global::Traq.Qall.Endpoints.EndpointsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rooms property</summary>
        public global::Traq.Qall.Rooms.RoomsRequestBuilder Rooms
        {
            get => new global::Traq.Qall.Rooms.RoomsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The soundboard property</summary>
        public global::Traq.Qall.Soundboard.SoundboardRequestBuilder Soundboard
        {
            get => new global::Traq.Qall.Soundboard.SoundboardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The token property</summary>
        public global::Traq.Qall.Token.TokenRequestBuilder Token
        {
            get => new global::Traq.Qall.Token.TokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhook property</summary>
        public global::Traq.Qall.Webhook.WebhookRequestBuilder Webhook
        {
            get => new global::Traq.Qall.Webhook.WebhookRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Traq.Qall.QallRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QallRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/qall", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Traq.Qall.QallRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QallRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/qall", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
